
from LyricsPreprocessor import LyricsPreprocessor

class Commons:
    artists = None
    special_tokens = None


Commons.artists = [
    "Children of Bodom",
    "Bodom After Midnight",
    "Sinergy",
    "Kalmah",
    "Norther",
    "Skyfire",
    "Mors Principium Est",
    "Nekrogoblikon",
    "Dimmu Borgir",
    "System of a Down",
    "Slayer",
    "Eternal Tears Of Sorrow",
    "Iron Maiden",
    "Manowar",
    "Metallica",
    "Imperanon",
    "Frozen Crown",
    "Bullet for My Valentine",
    "Alestorm",
    "Instorm",
    "In Flames",
    "Dark Tranquillity",
    "At The Gates",
    "Amorphis",
    "Megadeth",
    "Death",
    "Noumena",
    "Amon Amarth",
    "Arch Enemy",
    "Slipknot",
    "Avril Lavigne",
    "Wintersun",
    "Insomnium",
    "Omnium Gatherum",
    "Ensiferum",
    "The Black Dahlia Murder",
    "Cryhavoc",
    "Anthrax",
    "Megadeth",
    "Nox Aeterna",
    "Opeth",
    "Naildown",
    "Frozen Crown",
    "Aephanemer",
    "Pantera",
    "Dethklok",
    "Be'lakor",
    "Abyssos",
    "Ablaze My Sorrow",
    "AC/DC",
    "Alice Cooper",
    "All That Remains",
    "Amaranthe",
    "Andy Gillion",
    "As I Lay Dying",
    "August Burns Red",
    "Barathrum",
    "The Beatles",
    ### "Beneath The Dying Sky", ### No results found for 'Beneath The Dying Sky'. - todo: investigate
    "Beneath The Sky",
    "Between The Buried And Me",
    "Black Veil Brides",
    "Blink-182",
    "Bloodbath",
    "Bloodhound Gang",
    "Bloodred Hourglass",
    "Brymir",
    "Burn Down Eden",
    "Cannibal Corpse",
    "Dying Fetus",
    "Carcass",
    "Countless Skies",
    "Cradle Of Filth",
    "Crownshift",
    "Crypta",
    "Cryptopsy",
    "Dark The Suns",
    "Deicide",
    "Dissection",
    "DragonForce",
    "Dream Theater",
    "Edge Of Sanity",
    "Eleine",
    "Eluveitie",
    "Emperor",
    "Enshine",
    "Eternal Storm",
    "The Faceless",
    "Fractal Gates",
    "Frantic Amber",
    "Gates Of Ishtar",
    "Gloryhammer",
    "Djerv",
    "Gods Tower",
    "Graveworm",
    "Grima",
    "The Halo Effect",
    "Heaven Shall Burn",
    "Hypocrisy",
    "Imperial Age",
    "Infected Rain",
    "In Thousand Lakes",
    "Korn",
    "Lamb Of God",
    "Lorna Shore",
    "Lunarsea",
    "Mayhem",
    "Meshuggah",
    "Moonshade",
    "Moonsorrow",
    "Morbid Angel",
    "Mortician",
    "Motorhead",
    "MyGrain",
    "Naildown",
    "Nanowar Of Steel",
    "Napalm Death",
    "Nargaroth",
    "Necrophagist",
    "Nervosa",
    "Nightwish",
    "Nile",
    "Nocturna",
    "Obituary",
    "Okilly Dokilly",
    "Party Cannon",
    "Perpetual Night",
    "Pizza Death",
    "Poison",
    "Powerwolf",
    "Rage", ## -> Kid Cudi ??? todo: investigate
    "Rage Against The Machine",
    "Ramones",
    "Rings Of Saturn",
    "Rivers Of Nihil",
    "Rotting Christ",
    "Running Wild",
    "Ryujin",
    "Gyze",
    "Sabaton",
    "Satanic North",
    "Satyricon",
    "Scar Symmetry",
    "Sentenced",
    "Sepultura",
    "Septicflesh",
    "Serenity In Murder",
    "Shylmagoghnar",
    "Sleep Token",
    "Soilwork",
    "Sonata Arctica",
    "Soulfly",
    "Spiritbox",
    "Spoil Engine",
    "Suffocation",
]

Commons.special_tokens = {
    "additional_special_tokens": [
        LyricsPreprocessor.MARKER_END_OF_LINE,
        LyricsPreprocessor.MARKER_SONG_NAME_START,
        LyricsPreprocessor.MARKER_SONG_NAME_END,
        LyricsPreprocessor.MARKER_SONG_START,
        LyricsPreprocessor.MARKER_SONG_END,
        LyricsPreprocessor.PAD_TOKEN,
        LyricsPreprocessor.bos_token,
        LyricsPreprocessor.eos_token,
        LyricsPreprocessor.unk_token,
    ]
}