
class Commons:
    artists = None


Commons.artists = [
    # "Children of Bodom",
    # "Bodom After Midnight",
    # "Sinergy",
    # "Kalmah",
    # "Norther",
    # "Skyfire",
    # "Mors Principium Est",
    # "Nekrogoblikon",
    # "Dimmu Borgir",
    # "System of a Down",
    "Slayer",
    "Eternal Tears Of Sorrow",
    "Iron Maiden",
    "Manowar",
    "Metallica",
    "Imperanon",
    "Frozen Crown",
    "Bullet for My Valentine",
    "Alestorm",
    "Instorm",
    "In Flames",
    "Dark Tranquillity",
    "At The Gates",
    "Amorphis",
    "Megadeth",
    "Death",
    "Noumena",
    "Amon Amarth",
    "Arch Enemy",
    "Slipknot",
    "Avril Lavigne",
    "Wintersun",
    "Insomnium",
    "Omnium Gatherum",
    "Ensiferum",
    "The Black Dahlia Murder",
]